### ISSUE TITLE
Need front-end user text for login screen

### ISSUE THREAD

**Issue by nathanhilbert** [USStateDept/FPA_Core#176]
Should include
- who can sign up related to #98
- must use email address
- and the process that they will receive an email and need to verify.
- also what they get by signing in.  At the moment saved vizes?

**Comment by dstepp** [comment]
FYI, be more descriptive with the issue titles.

Do you need someone to write the content for this? I would assume this is a F issue. @leroybryant can you confirm?

**Comment by nathanhilbert** [comment]
I was thinking this would be passed on to F.  I can write the error messages, but they will need to provide why it's USG only.

**Comment by jonvan5** [comment]
We can draft text. Can you provide more details on what is needed? An example would be helpful. 

Also, for the beta, we are interested offering login benefits with limited functionality so that effort can be focused on higher-priority areas. We tried to identify valuable features that aren't too technically difficult: 
o   Receive email alerts of site updates, including updated data
o   Ability to save queries 
o   Ability to save visualizations 
o   Access to USG country groups of interest (e.g., FTF countries)
o   Create and save custom regions

However, feel free to let us know if these features are more complex than we realize. For the forum aspect-- we may want to have a discussion of the long-term vision for it before too much work is done on it.

**Comment by dstepp** [comment]
@jonvan5 we are looking for content on this page: http://finddev.edip-maps.net/login Specifically, "Please Sign into Find. This application is under development, so it may have some quirks and odd behaviours."

The other functionality you mention can be broken into other issues.

**Comment by aminvafa** [comment]
Change text to the following:

Sign into FIND. This application is under development, so please excuse issues you may encounter.

**Comment by ghost** [comment]
@aminvafa
I just changed it to the text you indicated.
