### ISSUE TITLE
Quality Assurance Check/Re-ingest CDA Indicator Data

### ISSUE THREAD

**Issue by fucc1** [USStateDept/FPA_Core#189]
In the original data that was provided (via CSV files), there was erroneous data that might be causing the incorrect display of the CDA data.   F/PA can provide amended data if need be.

**Comment by aminvafa** [comment]
Some of the CSV files had multiple tables in one sheet, and the system loaded all of that data instead of just the uppermost table on the sheet. F/PA can provide more details in-person, as well as new CSV files to ingest.

**Comment by dstepp** [comment]
The list of indicators available on http://finddev.edip-maps.net/data does not completely match http://finddev.edip-maps.net/admin/sourcesadmin/

**Comment by nathanhilbert** [comment]
Suggesting to break into multiple issues
- [ ] data QA script with log output
- [ ] UI to get the output from the QA script for a single data source
- [ ] Re-ingest CDA data 
- [ ] Reformat the CDA CSVs into a format easily ingested (f required)

**Comment by dstepp** [comment]
@Nathnhilbert can we just do a rough reingestion to make sure all the data is loaded accurately? Then we can start working on improving the UI for data loading. Thoughts?

**Comment by nathanhilbert** [comment]
A better order might be this.  I don't think the transformation process is the issue, but rather the original data.  I can try to do a rough reingestion with new data (see second point).  In the end, we need better qa processes after data are loaded (rows loaded vs. rows available, countries matched, years available, error logs).
- [x] UI to get the output from the QA script for a single data source in order to find which datasets have erroneous data.  The UI is a link that fetches an individual dataset from the [script](https://github.com/USStateDept/FPA_Core/blob/master/openspending/command/importer.py#L284)   
- [x] Reformat the CDA CSVs into a format easily ingested (f required) in order to upload one CSV per dataset with one table.  
- [x] Rough reingestion of new CDA data
- [x] Examine QA outputs with the new data to verify that data are correct

How's that sound?

**Comment by dstepp** [comment]
That looks great. Do you (we) have the correct format for the CDA data?

**Comment by nathanhilbert** [comment]
Um... I think the original is in the shared drive last I knew.  @leroybryant would know better where the split out version is.

**Comment by aminvafa** [comment]
If we need to re-send the CDA data, we can do that.

**Comment by nathanhilbert** [comment]
Thanks @aminvafa . We have the CDA data, it just needed a little more cleaning.  The continued conversation was over email.

**Comment by aminvafa** [comment]
No problem. After I realized that some of the CSV files had multiple tables in them (which likely contributed to some of the incorrect data inputs), I made cleaner CSV files with metadata in the first few rows + only one table.

**Comment by nathanhilbert** [comment]
Uploaded the cleaned files, transformed them, and loaded them into the system.  The QA checks that there is now one country per year for each indicator.
