### ISSUE TITLE
As a user, I want the Internal Server Error fixed when logging in

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#245]
I'm trying to log in this morning with my steppdn@state.gov email and it is giving me the server error.

**Comment by nathanhilbert** [comment]
relates to #236.  I had to change a few settings for the forums for authentication.  I can check this out once I have a production database (already requested from @brandtheisey ).

**Comment by nathanhilbert** [comment]
Looks like your password was not set when you registered, which is part of the not-so-clear workflow. A user should see a message though that they have not verified their email using the link sent to their email.  
 The current workflow is after you register your email and user name, you are directed to a page as shown below.  This would actually arrive in your email, and that page would say please check your email.  The user then clicks the link in the email in order to verify they actually have a .gov account, and they are asked to set their password.  Key point here is **it might be time to set up the email server and put the production messages**.  This would require us to have the find.state.gov domain name, and we can set up the AWS SMS.  This requires us to set some text domain records for AWS to verify the domain name.  
Temporarily, I'll erase your account on production, and maybe you can try again make sure to click the verify link as shown below.  
![image](https://cloud.githubusercontent.com/assets/718283/9152697/17fe25ca-3df8-11e5-9ad1-a3249dbc6d74.png)
