### ISSUE TITLE
As a politician, I would like a map disclaimer.

### ISSUE THREAD

**Issue by dstepp** [USStateDept/FPA_Core#297]

**Comment by aminvafa** [comment]
For now, let's add something like this:

Boundary representation on maps is not necessarily authoritative or final. Additionally, subnational boundaries may appear even though no subnational data are available in FIND. If you select a subnational area, you will be shown national information. For more information about the geography tile layer, visit openstreetmap.org.

**Comment by leroybryant** [comment]
@aminvafa I changed the basemap in a commit I did yesterday.  Please let me know if it is ok.  It is the one labelled acetate.basemap here.  http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by aminvafa** [comment]
@leroybryant acetate.basemap is much better because it doesn't have all of the subnational stuff. but it still doesn't include Western Sahara, and it needs to for the map to be done. off the top of my head, i can't think of any other territories it doesn't include (or does and shouldn't, etc.), but we'll still need a disclaimer if we don't have a shapefile that matches with DoS's independent states and areas of special sovereignty.

**Comment by aminvafa** [comment]
if the office of the geographer and the hiu both use openstreetmap for their work, i'd have to assume they have an open source basemap that covers all of this (like an LSIB openstreetmap basemap or something). maybe try reaching out to them?

**Comment by leroybryant** [comment]
I'm using a layer based on the their data.  acetate.basemap will be underneath.  I will reach out though to them though.
