### ISSUE TITLE
Bubble charts don't display data

### ISSUE THREAD

**Issue by aminvafa** [USStateDept/FPA_Core#314]
Load time is slow, and each axis loads (and responds to selecting/unselecting countries), but no actual points appear on the chart. I tested with 3 robust indicators: GDP, total; Life Expectancy (CDA); and Population.

**Comment by aminvafa** [comment]
![bubble chart](https://cloud.githubusercontent.com/assets/10505111/9661793/59d99682-522a-11e5-8b46-2fb649b29577.png)

**Comment by sc0ttius** [comment]
It appears that this chart failed because there were no data points in 2014 for life expectancy. However, in testing, I found that the year slider was not functioning properly. I will close this ticket be cause I resolved the issue with the year slider. If you do the same query and move the slider to a date that has all three data points, the chart will display.

That said, a new issue was discovered concerning the data range and missing data points. I will create a new ticket for these issues.
